export enum InternalSvgIcon {
	GOAT = 'goat',
	GONG = 'gong',
	ONI = 'oni',
	SINS_ANGER = 'sins/anger',
	SINS_ATTACHMENT = 'sins/attachment',
	SINS_DECEIT = 'sins/deceit',
	SINS_DELUSION = 'sins/delusion',
	SINS_EGO = 'sins/ego',
	SINS_ENVY = 'sins/envy',
	SINS_FEAR = 'sins/fear',
	SINS_GLUTTONY = 'sins/gluttony',
	SINS_GREED = 'sins/greed',
	SINS_LUST = 'sins/lust',
	SINS_PRIDE = 'sins/pride',
	SINS_SLOTH = 'sins/sloth',
	SINS_WRATH = 'sins/wrath',
	SNAKE = 'snake',
	STACK = 'stack',
	WHEEL = 'wheel',
}
