version: 2

updates:
    -   package-ecosystem: "npm"
        directory: "/"
        open-pull-requests-limit: 0
        schedule:
            interval: "daily"
            time: "08:00"
            timezone: "America/Denver"
        labels:
            - "type: Dependencies :arrow_up:"
