name: Auto Merge Dependabot

on:
    pull_request_target:

jobs:
    auto-merge:
        name: Auto Merge Dependabot
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}
            -   uses: ahmadnassri/action-dependabot-auto-merge@master
                with:
                    target: minor
                    command: squash and merge
                    github-token: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}
