name: Bump Version & Deploy Production

on: [ push ]
#on:
#    push:
#        branches: [ master ]

jobs:
    deploy-production:
        name: "Deploy Production"
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Automated Version Bump
                uses: phips28/gh-action-bump-version@v7.1.0

            -   name: Cache Node Modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.OS }}-build-${{ env.cache-name }}-
                        ${{ runner.OS }}-build-
                        ${{ runner.OS }}-

            -   name: Install dependencies
                run: npm install

            -   name: Build Production
                run: npm run build --prod

            -   name: Deploy to Firebase Hosting
                uses: w9jds/firebase-action@master
                with:
                    args: deploy --only hosting
                env:
                    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

#            -   name: Deploy to Firebase Hosting
#                uses: FirebaseExtended/action-hosting-deploy@v0
#                with:
#                    repoToken: "${{ secrets.GITHUB_TOKEN }}"
#                    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
#                    channelId: live
