
name: Buid & Test

on: [push]

defaults:
  run:
    shell: pwsh
    working-directory: ./

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Runs the Jasmine Tests
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
        
