name: Test GPG

on:
    push:
        paths:
            - '.github/workflows/test-gpg.yml'

jobs:
    test-gpg:
        name: Test GPG
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}

            -   run: which -a gpg
            -   run: which -a gpg.conf

            -   name: Sign Commit
                uses: crazy-max/ghaction-import-gpg@master
                with:
                    gpg-private-key: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}
                    passphrase: ${{ secrets.ACTIONS_GPG_PASSPHRASE }}
                    git-user-signingkey: true
                    git-commit-gpgsign: true
                    git-push-gpgsign: true

            -   name: Add GPG to Git Config
                run: |
                    git config gpg.program $(which gpg)
                    echo "no-tty" >> ~/.gnupg/gpg.conf
            -   run: git config --list --show-origin

            -   name: Test Signing a Commit
                run: git commit --allow-empty -m "signed actions commit"
