name: Test GPG

on:
    push:
        paths:
            - '.github/workflows/test-gpg.yml'

jobs:
    test-gpg:
        name: Test GPG
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}

            -   name: Sign Commit
                uses: crazy-max/ghaction-import-gpg@master
                with:
                    gpg_private_key: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}
                    passphrase: ${{ secrets.ACTIONS_GPG_PASSPHRASE }}
                    git_user_signingkey: true
                    git_commit_gpgsign: true

            -   run: which -a gpg
            -   run: docker container ls -q

            -   name: Add GPG to Git Config
                run: |
                    git config gpg.program $(which gpg)
                    echo "no-tty" >> ~/.gnupg/gpg.conf

            -   run: git config --list --show-origin

            -   name: Test Automated Version Bump
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}
                    GITHUB_USER: ${{ secrets.REPOSITORY_ACTIONS_USER }}
                    GITHUB_EMAIL: ${{ secrets.REPOSITORY_ACTIONS_EMAIL }}
                with:
                    minor-wording: 'feature: '
                    skip-tag: true

