name: Test GPG
on: [ push ]
jobs:
    test-gpg:
        name: Test GPG
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}

            -   run: git config --get gpg.program
            -   run: which gpg

            -   name: Sign Commit
                uses: crazy-max/ghaction-import-gpg@master
                with:
                    gpg-private-key: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}
                    passphrase: ${{ secrets.ACTIONS_GPG_PASSPHRASE }}
                    git-user-signingkey: true
                    git-commit-gpgsign: true
                    git-push-gpgsign: true

            -   run: git config --get gpg.program
            -   run: which gpg

            -   run: git config gpg.program $(which gpg)
            -   run: git config --get gpg.program

