name: Lint, Build, & Test

on:
    push:

jobs:
    test:
        name: Lint, Build, & Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install dependencies
                run: npm install

            -   name: Lint
                run: npm run lint

            -   name: Build
                run: npm run build -- --configuration=ci

            -   name: Test
                run: npm test -- --configuration=ci
