name: Test Content

on:
    push:
        paths:
            - 'src/assets/images/**'
            - 'src/scripts/**'

jobs:
    test:
        name: Test Content
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Branch
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install ImageMagick
                timeout-minutes: 2
                run: |
                    sudo apt-get install imagemagick;
                    identify --version;

            -   name: Import Content
                run: npm run content
